
import { ResumeData } from './types';

export const INITIAL_RESUME_DATA: ResumeData = {
  id: 'temp-1',
  title: '',
  theme: 'minimalist',
  fullName: '',
  email: '',
  phone: '',
  location: '',
  linkedin: '',
  website: '',
  summary: '',
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: []
};




export const SAMPLE_RESUMES: ResumeData[] = [
  {
    id: 'sample-tech',
    title: 'Software Architect',
    theme: 'modern',
    fullName: 'Jordan Smith',
    email: 'jordan@tech.io',
    phone: '555-4444',
    location: 'Austin, TX',
    linkedin: 'linkedin.com/in/jsmith',
    website: 'jsmith.io',
    summary: 'Cloud infrastructure expert with a focus on high-availability systems and distributed architectures.',
    experience: [],
    education: [],
    skills: ['Go', 'Kubernetes', 'AWS', 'System Design'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-marketing',
    title: 'Growth Lead',
    theme: 'minimalist',
    fullName: 'Elena Rodriguez',
    email: 'elena@growth.co',
    phone: '555-9999',
    location: 'New York, NY',
    linkedin: 'linkedin.com/in/erodriguez',
    website: '',
    summary: 'Growth-focused marketing leader with experience in scaling SaaS startups from $1M to $50M ARR.',
    experience: [],
    education: [],
    skills: ['SEO', 'SEM', 'Content Strategy', 'Data Analytics'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-data',
    title: 'Senior Data Scientist',
    theme: 'bold',
    fullName: 'David Park',
    email: 'david.park@data-intel.com',
    phone: '555-1234',
    location: 'Seattle, WA',
    linkedin: 'linkedin.com/in/dpark-data',
    website: 'dpark.me',
    summary: 'Machine learning expert specializing in predictive modeling and natural language processing.',
    experience: [],
    education: [],
    skills: ['Python', 'PyTorch', 'SQL', 'Deep Learning'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-finance',
    title: 'Financial Analyst',
    theme: 'executive',
    fullName: 'Sarah Thompson',
    email: 's.thompson@wealth.com',
    phone: '555-8888',
    location: 'Chicago, IL',
    linkedin: 'linkedin.com/in/sthompson-finance',
    website: '',
    summary: 'Detail-oriented analyst with a track record of identifying $10M+ in cost-saving opportunities.',
    experience: [],
    education: [],
    skills: ['Financial Modeling', 'Excel Mastery', 'Risk Assessment'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-healthcare',
    title: 'Board Certified Physician',
    theme: 'classic',
    fullName: 'Dr. James Wilson',
    email: 'j.wilson.md@hospital.org',
    phone: '555-0000',
    location: 'Boston, MA',
    linkedin: '',
    website: '',
    summary: 'Dedicated healthcare professional with 15 years of experience in internal medicine and patient care.',
    experience: [],
    education: [],
    skills: ['Patient Diagnosis', 'Medical Research', 'Team Leadership'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-legal',
    title: 'Corporate Attorney',
    theme: 'executive',
    fullName: 'Catherine Vance',
    email: 'c.vance@law-associates.com',
    phone: '555-7777',
    location: 'Washington, D.C.',
    linkedin: 'linkedin.com/in/cvance-law',
    website: '',
    summary: 'Expert in corporate governance, mergers, and intellectual property law for Fortune 500 companies.',
    experience: [],
    education: [],
    skills: ['Contract Law', 'Litigation', 'Legal Compliance'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-creative',
    title: 'Creative Director',
    theme: 'bold',
    fullName: 'Maya Brooks',
    email: 'maya@studio-creative.com',
    phone: '555-3333',
    location: 'Los Angeles, CA',
    linkedin: 'linkedin.com/in/mbrooks-creative',
    website: 'mbrooks.design',
    summary: 'Award-winning director specializing in brand identity and visual storytelling for luxury brands.',
    experience: [],
    education: [],
    skills: ['Art Direction', 'Brand Strategy', 'Adobe Suite'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-hr',
    title: 'HR Operations Manager',
    theme: 'minimalist',
    fullName: 'Robert Chen',
    email: 'r.chen@enterprise.com',
    phone: '555-2222',
    location: 'Denver, CO',
    linkedin: 'linkedin.com/in/rchen-hr',
    website: '',
    summary: 'Strategic HR leader focused on talent acquisition and building inclusive workplace cultures.',
    experience: [],
    education: [],
    skills: ['Talent Management', 'Employee Relations', 'HRIS'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-sales',
    title: 'Senior Account Executive',
    theme: 'modern',
    fullName: 'Mark Henderson',
    email: 'm.henderson@salesforce.com',
    phone: '555-1111',
    location: 'Atlanta, GA',
    linkedin: 'linkedin.com/in/mhenderson-sales',
    website: '',
    summary: 'High-performing sales professional with 8 consecutive years of exceeding $2M annual quotas.',
    experience: [],
    education: [],
    skills: ['B2B Sales', 'Negotiation', 'CRM Strategy'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  },
  {
    id: 'sample-edu',
    title: 'Mathematics Professor',
    theme: 'classic',
    fullName: 'Alice Wright',
    email: 'a.wright@university.edu',
    phone: '555-4444',
    location: 'Cambridge, MA',
    linkedin: '',
    website: '',
    summary: 'Passionate educator with a doctorate in Pure Mathematics and 10 published research papers.',
    experience: [],
    education: [],
    skills: ['Curriculum Design', 'Educational Research', 'Mentorship'],
    projects: [],
    certifications: [],
    createdAt: 'Sample'
  }
];
